remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
title: Reading Groups at the Faculty of Engineering, University of Freiburg
description: Information about the reading groups at the Faculty of Engineering, University of Freiburg
show_downloads: false